--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-09-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BODY_TYPE
--------------------------------------------------------

  CREATE TABLE "HR"."BODY_TYPE" 
   (	"USER_BODY_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.BODY_TYPE
SET DEFINE OFF;
Insert into HR.BODY_TYPE (USER_BODY_TYPE) values ('BODY_TYPE_TEST');
Insert into HR.BODY_TYPE (USER_BODY_TYPE) values ('I');
Insert into HR.BODY_TYPE (USER_BODY_TYPE) values ('O');
Insert into HR.BODY_TYPE (USER_BODY_TYPE) values ('V');
--------------------------------------------------------
--  DDL for Index SYS_C007078
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007078" ON "HR"."BODY_TYPE" ("USER_BODY_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BODY_TYPE
--------------------------------------------------------

  ALTER TABLE "HR"."BODY_TYPE" ADD PRIMARY KEY ("USER_BODY_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
