--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-09-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GENRE
--------------------------------------------------------

  CREATE TABLE "HR"."GENRE" 
   (	"GENRE_NAME" VARCHAR2(20 BYTE), 
	"USER_BODY_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.GENRE
SET DEFINE OFF;
Insert into HR.GENRE (GENRE_NAME,USER_BODY_TYPE) values ('GENRE_TEST','BODY_TYPE_TEST');
Insert into HR.GENRE (GENRE_NAME,USER_BODY_TYPE) values ('classic','V');
Insert into HR.GENRE (GENRE_NAME,USER_BODY_TYPE) values ('classiccasual','V');
Insert into HR.GENRE (GENRE_NAME,USER_BODY_TYPE) values ('minimal','I');
Insert into HR.GENRE (GENRE_NAME,USER_BODY_TYPE) values ('street','I');
Insert into HR.GENRE (GENRE_NAME,USER_BODY_TYPE) values ('workwear','O');
Insert into HR.GENRE (GENRE_NAME,USER_BODY_TYPE) values ('amecaji','O');
--------------------------------------------------------
--  DDL for Index SYS_C007086
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007086" ON "HR"."GENRE" ("GENRE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GENRE
--------------------------------------------------------

  ALTER TABLE "HR"."GENRE" ADD PRIMARY KEY ("GENRE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."GENRE" MODIFY ("USER_BODY_TYPE" NOT NULL ENABLE);
