--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-09-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LIKETO
--------------------------------------------------------

  CREATE TABLE "HR"."LIKETO" 
   (	"LIKE_NUM" NUMBER, 
	"BOARD_NUM" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"LIKE_CHECK" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.LIKETO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007234
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007234" ON "HR"."LIKETO" ("LIKE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LIKETO
--------------------------------------------------------

  ALTER TABLE "HR"."LIKETO" ADD PRIMARY KEY ("LIKE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."LIKETO" MODIFY ("LIKE_CHECK" NOT NULL ENABLE);
  ALTER TABLE "HR"."LIKETO" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."LIKETO" MODIFY ("BOARD_NUM" NOT NULL ENABLE);
