--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-09-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SELECTED
--------------------------------------------------------

  CREATE TABLE "HR"."SELECTED" 
   (	"SELECT_NUM" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(30 BYTE), 
	"TOP_NUM" VARCHAR2(20 BYTE), 
	"BOTTOM_NUM" VARCHAR2(20 BYTE), 
	"OUTER_NUM" VARCHAR2(20 BYTE), 
	"SHOES_NUM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.SELECTED
SET DEFINE OFF;
Insert into HR.SELECTED (SELECT_NUM,USER_ID,TOP_NUM,BOTTOM_NUM,OUTER_NUM,SHOES_NUM) values ('2','test1','376','376','376','352');
Insert into HR.SELECTED (SELECT_NUM,USER_ID,TOP_NUM,BOTTOM_NUM,OUTER_NUM,SHOES_NUM) values ('18','gaekokdj','1723','808','1028','888');
Insert into HR.SELECTED (SELECT_NUM,USER_ID,TOP_NUM,BOTTOM_NUM,OUTER_NUM,SHOES_NUM) values ('21','ture1029','2517','1324','1362','971');
Insert into HR.SELECTED (SELECT_NUM,USER_ID,TOP_NUM,BOTTOM_NUM,OUTER_NUM,SHOES_NUM) values ('14','ture1029','2698','1378','1369','1021');
Insert into HR.SELECTED (SELECT_NUM,USER_ID,TOP_NUM,BOTTOM_NUM,OUTER_NUM,SHOES_NUM) values ('22','gaekokdj','2104','866','1223','758');
Insert into HR.SELECTED (SELECT_NUM,USER_ID,TOP_NUM,BOTTOM_NUM,OUTER_NUM,SHOES_NUM) values ('9','test1','834','697','795','369');
Insert into HR.SELECTED (SELECT_NUM,USER_ID,TOP_NUM,BOTTOM_NUM,OUTER_NUM,SHOES_NUM) values ('10','test1','1129','605','704','464');
Insert into HR.SELECTED (SELECT_NUM,USER_ID,TOP_NUM,BOTTOM_NUM,OUTER_NUM,SHOES_NUM) values ('11','test1','406','406','406','357');
Insert into HR.SELECTED (SELECT_NUM,USER_ID,TOP_NUM,BOTTOM_NUM,OUTER_NUM,SHOES_NUM) values ('29','gaekokdj','704','295','198','328');
Insert into HR.SELECTED (SELECT_NUM,USER_ID,TOP_NUM,BOTTOM_NUM,OUTER_NUM,SHOES_NUM) values ('13','ture1029','2541','1318','1344','971');
--------------------------------------------------------
--  DDL for Index SYS_C007184
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007184" ON "HR"."SELECTED" ("SELECT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SELECTED
--------------------------------------------------------

  ALTER TABLE "HR"."SELECTED" ADD PRIMARY KEY ("SELECT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SELECTED" MODIFY ("SHOES_NUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."SELECTED" MODIFY ("OUTER_NUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."SELECTED" MODIFY ("BOTTOM_NUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."SELECTED" MODIFY ("TOP_NUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."SELECTED" MODIFY ("USER_ID" NOT NULL ENABLE);
