--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-09-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERTABLE
--------------------------------------------------------

  CREATE TABLE "HR"."USERTABLE" 
   (	"USER_ID" VARCHAR2(30 BYTE), 
	"USER_BODY_TYPE" VARCHAR2(20 BYTE), 
	"USER_PW" VARCHAR2(20 BYTE), 
	"USER_MAIL" VARCHAR2(20 BYTE), 
	"BLACKLIST" CHAR(1 BYTE) DEFAULT 'F'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.USERTABLE
SET DEFINE OFF;
Insert into HR.USERTABLE (USER_ID,USER_BODY_TYPE,USER_PW,USER_MAIL,BLACKLIST) values ('gaekokdj','I','1234','gaekokdj@naver.com','F');
Insert into HR.USERTABLE (USER_ID,USER_BODY_TYPE,USER_PW,USER_MAIL,BLACKLIST) values ('ture1029','O','1234','ture1029@gmail.com','F');
Insert into HR.USERTABLE (USER_ID,USER_BODY_TYPE,USER_PW,USER_MAIL,BLACKLIST) values ('test1','V','1234','test1@hanmail.net','F');
--------------------------------------------------------
--  DDL for Index SYS_C007083
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007083" ON "HR"."USERTABLE" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERTABLE
--------------------------------------------------------

  ALTER TABLE "HR"."USERTABLE" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
